pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }

    parameters {
        choice(name: 'action', choices: ['apply', 'destroy'], description: 'Pick something')
    }
    
    options {
        ansiColor('xterm')
        timeout(time: 1, unit: 'HOURS') 
        disableConcurrentBuilds() //It wont allow two builds at a time
    }

    
    //BUILD
    stages {
        stage('Init') {
            steps {
                sh """
                    cd 01-vpc
                    terraform init
                """               
            }
        }
        stage('Plan') {
            steps {
                sh """
                    cd 01-vpc
                    terraform plan
                """   
            }
        }
        
        stage('Deploy') {

            when {

                "${params.action}" == 'apply'
            }
            
            input {
                message "Should we continue?"
                ok "Yes, we should."
                // submitter "alice,bob"
                // parameters {
                //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                // }
            }
            
            steps {
                sh """
                    cd 01-vpc
                    terraform apply -auto-approve
                """   
            }
        }      

        stage('Destroy') {

            when {

                "${params.action}" == 'destroy'
            }
            
            input {
                message "Should we continue?"
                ok "Yes, we should."
                // submitter "alice,bob"
                // parameters {
                //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                // }
            }
            
            steps {
                sh """
                    cd 01-vpc
                    terraform destroy -auto-approve
                """   
            }
        }        
    }
    // POST BUILD
    post { 
        always { 
            echo 'I will always say Hello!!'
        }

        failure { 
            echo 'this runs when pipeline is failed, used generally to send alerts'
        }
        success { 
            echo 'I will always say Hello when pipeline is success'
        }
    }
}